### ISSUE TITLE
[Tracker] The great GCC 10 rebuild.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#146]
- [x] core/binutils
- [x] core/bison
- [x] core/busybox
- [x] core/dhcpcd
- [x] core/e2fsprogs
- [x] core/eudev
- [x] core/flex
- [x] core/grub
- [x] core/libressl
- [x] core/m4
- [x] extra/acpid
- [x] extra/alsa-lib
- [x] extra/alsa-utils
- [x] extra/atk
- [x] extra/autoconf
- [x] extra/automake
- [x] extra/cairo
- [x] extra/cbindgen
- [x] extra/clang
- [x] extra/cmake
- [x] extra/cryptsetup
- [x] extra/dosfstools
- [x] extra/efibootmgr
- [x] extra/efivar
    - Compiler bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=45180
- [x] extra/eiwd
- [x] extra/expat
- [x] extra/extra-cmake-modules
- [x] extra/falkon
- [x] extra/ffmpeg
- [x] extra/firefox
- [x] extra/firefox-privacy
- [x] extra/fontconfig
- [x] extra/freetype-harfbuzz
- [x] extra/fribidi
- [x] extra/gdk-pixbuf
- [x] extra/giflib
- [x] extra/glib
- [x] extra/gnupg1
    - `-fcommon`.
- [x] extra/gtk+2
- [x] extra/gtk+3
- [x] extra/hicolor-icon-theme
- [x] extra/intel-media-driver
    - `error: ‘%s’ directive argument is null`
- [x] extra/intel-vaapi-driver
    `-fcommon`.
- [x] extra/json-c
- [x] extra/lame
- [x] extra/libaio
- [x] extra/libarchive
- [x] extra/libass
- [x] extra/libdrm
- [x] extra/libepoxy
- [x] extra/liberation-fonts
- [x] extra/libevdev
- [x] extra/libevent
- [x] extra/libffi
- [x] extra/libinput
- [x] extra/libjpeg-turbo
- [x] extra/libogg
- [x] extra/libpng
- [x] extra/libtheora
- [x] extra/libtool
- [x] extra/libva
- [x] extra/libva-utils
- [x] extra/libvorbis
- [x] extra/libvpx
- [x] extra/libwebp
- [x] extra/libxml2
- [x] extra/llvm
- [x] extra/lvm2
- [x] extra/mesa
    - `-fcommon`.
- [x] extra/meson
- [x] extra/mpv
- [x] extra/mtdev
- [x] extra/nasm
- [x] extra/ncurses
- [x] extra/nodejs
- [x] extra/nss
- [x] extra/opendoas
- [x] extra/openssh
- [x] extra/opus
- [x] extra/pango
- [x] extra/popt
- [x] extra/python
- [x] extra/python-mako
- [x] extra/python2
- [x] extra/qt5
- [x] extra/qt5-declarative
- [x] extra/qt5-svg
- [x] extra/qt5-webchannel
- [x] extra/qt5-webengine
- [x] extra/qt5-x11extras
- [x] extra/rust
- [x] extra/samurai
- [x] extra/shared-mime-info
- [x] extra/sqlite
- [x] extra/sudo
- [x] extra/tiff
- [x] extra/tzdata
- [x] extra/vim
- [x] extra/x264
- [x] extra/x265
- [x] extra/xvidcore
- [x] extra/yasm
- [x] extra/zip
- [x] testing/gcc
- [x] xorg/libICE
- [x] xorg/libSM
- [x] xorg/libX11
- [x] xorg/libXScrnSaver
- [x] xorg/libXau
- [x] xorg/libXcomposite
- [x] xorg/libXcursor
- [x] xorg/libXdamage
- [x] xorg/libXext
- [x] xorg/libXfixes
- [x] xorg/libXfont2
- [x] xorg/libXft
- [x] xorg/libXi
- [x] xorg/libXinerama
- [x] xorg/libXrandr
- [x] xorg/libXrender
- [x] xorg/libXt
    - Compiler bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=45180
    - Patch: https://gitlab.freedesktop.org/xorg/lib/libxt/commit/f3079e509c5cf60042ae2261499ee13b6b02498a.patch
- [x] xorg/libXtst
- [x] xorg/libXxf86vm
- [x] xorg/libfontenc
- [x] xorg/libpciaccess
- [x] xorg/libxcb
- [x] xorg/libxkbcommon
- [x] xorg/libxkbfile
- [x] xorg/libxshmfence
- [x] xorg/pixman
- [x] xorg/setxkbmap
- [x] xorg/sowm
- [x] xorg/st
- [x] xorg/xauth
- [x] xorg/xbitmaps
- [x] xorg/xcb-proto
- [x] xorg/xcb-util
- [x] xorg/xcb-util-cursor
- [x] xorg/xcb-util-image
- [x] xorg/xcb-util-keysyms
- [x] xorg/xcb-util-renderutil
- [x] xorg/xcb-util-wm
- [x] xorg/xev
- [x] xorg/xf86-input-libinput
- [x] xorg/xf86-video-amdgpu
- [x] xorg/xf86-video-ati
- [x] xorg/xf86-video-intel
    - `-fcommon`.
- [x] xorg/xf86-video-nouveau
- [x] xorg/xf86-video-vesa
- [x] xorg/xinit
- [x] xorg/xinput
- [x] xorg/xkbcomp
- [x] xorg/xkeyboard-config
- [x] xorg/xorg-server
- [x] xorg/xorg-util-macros
- [x] xorg/xorgproto
- [x] xorg/xprop
- [x] xorg/xrandr
- [x] xorg/xrdb
- [x] xorg/xset
- [x] xorg/xsetroot
- [x] core/baseinit
- [x] core/baselayout
- [x] core/bzip2
- [x] core/curl
- [x] core/gcc
- [x] core/git
- [x] core/gzip
- [x] core/kiss
- [x] core/kiss-utils
- [x] core/libelf
- [x] core/libnl
- [x] core/linux-headers
- [x] core/make
- [x] core/mandoc
- `-fcommon`.
- [x] core/musl
- [x] core/openresolv
- [x] core/perl
- [x] core/pkgconf
- [x] core/rsync
- [x] core/util-linux
- [x] core/wpa_supplicant
- [x] core/xz
- [x] core/zlib
- [x] extra/ccache
- [x] extra/firefox-bin
- [x] extra/gperf
- [x] xorg/libXmu
- [x] xorg/xtrans
