### ISSUE TITLE
[Tracker] What depends on libtool?

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#159]
Can it be relegated to Community?

- [x] acpid
- [x] alsa-lib
- [x] alsa-utils
- [ ] atk
- [x] autoconf
- [x] automake
- [x] baseinit
- [x] baselayout
- [x] binutils
- [x] bison
- [x] busybox
- [x] bzip2
- [x] cairo
- [x] cbindgen
- [x] ccache
- [ ] clang
- [ ] cmake
- [x] curl
- [x] dhcpcd
- [x] dosfstools
- [x] e2fsprogs
- [x] efibootmgr
- [x] efivar
- [x] eudev
- [x] expat
- [ ] ffmpeg
- [ ] firefox
- [x] firefox-bin
- [x] firefox-privacy
- [x] flex
- [x] fontconfig
- [x] freetype-harfbuzz
- [x] fribidi
- [ ] gcc
- [x] gdk-pixbuf
- [x] giflib
- [x] git
- [x] glib
- [x] gnupg1
- [x] gperf
- [ ] grub
- [ ] gtk+2
- [ ] gtk+3
- [x] gzip
- [x] hicolor-icon-theme
- [ ] intel-media-driver
- [ ] intel-vaapi-driver
- [x] kiss
- [ ] lame
- [x] libICE
- [x] libSM
- [x] libX11
- [x] libXScrnSaver
- [x] libXau
- [x] libXcomposite
- [x] libXcursor
- [x] libXdamage
- [x] libXext
- [x] libXfixes
- [x] libXfont2
- [x] libXft
- [x] libXi
- [x] libXinerama
- [x] libXmu
- [x] libXrandr
- [x] libXrender
- [x] libXt
- [x] libXtst
- [x] libXxf86vm
- [x] libass
- [x] libdrm
- [x] libelf
- [x] libepoxy
- [x] liberation-fonts
- [x] libevdev
- [x] libffi
- [x] libfontenc
- [x] libinput
- [x] libjpeg-turbo
- [ ] libogg
- [ ] libpciaccess
- [ ] libpng
- [ ] libressl
- [ ] libtheora
- [ ] libtool
- [ ] libva
- [ ] libva-utils
- [ ] libvorbis
- [ ] libvpx
- [ ] libwebp
- [x] libxcb
- [x] libxkbcommon
- [x] libxkbfile
- [x] libxml2
- [ ] libxshmfence
- [x] linux-headers
- [ ] llvm
- [ ] m4
- [ ] make
- [ ] mandoc
- [ ] mesa
- [ ] meson
- [ ] mpv
- [ ] mtdev
- [ ] musl
- [x] nasm
- [ ] ncurses
- [ ] nodejs
- [ ] opendoas
- [ ] openssh
- [ ] opus
- [x] pango
- [ ] perl
- [x] pixman
- [x] pkgconf
- [ ] python
- [ ] python-mako
- [ ] python2
- [x] rsync
- [ ] rust
- [x] samurai
- [x] setxkbmap
- [x] sowm
- [ ] sqlite
- [x] st
- [x] sudo
- [x] tiff
- [x] tzdata
- [x] util-linux
- [x] vim
- [x] wpa_supplicant
- [ ] x264
- [ ] x265
- [x] xauth
- [x] xbitmaps
- [x] xcb-proto
- [x] xcb-util
- [x] xcb-util-cursor
- [x] xcb-util-image
- [x] xcb-util-keysyms
- [x] xcb-util-renderutil
- [x] xcb-util-wm
- [x] xev
- [x] xf86-input-libinput
- [ ] xf86-video-amdgpu
- [ ] xf86-video-ati
- [ ] xf86-video-intel
- [ ] xf86-video-nouveau
- [x] xf86-video-vesa
- [x] xinit
- [x] xinput
- [x] xkbcomp
- [x] xkeyboard-config
- [x] xorg-server
- [x] xorg-util-macros
- [x] xorgproto
- [x] xprop
- [x] xrandr
- [x] xrdb
- [x] xset
- [x] xsetroot
- [x] xtrans
- [x] xvidcore
- [x] xz
- [x] yasm
- [x] zip
- [x] zlib

**Comment by dylanaraps** [comment]
It can
