### ISSUE TITLE
[Tracker] Can we purge perl?

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#162]
- [x] baseinit
- [x] baselayout
- [x] binutils
- [x] bison
- [x] busybox
- [x] bzip2
- [x] curl
- [x] dhcpcd
- [x] e2fsprogs
- [x] flex
- [x] gcc
- [x] git
- [x] grub
- [x] gzip
- [x] kiss
- [x] libelf
- [x] libressl
- [x] linux-headers
- [x] m4
- [x] make
- [x] musl
- [x] perl
- [x] pkgconf
- [x] rsync
    - One perl script during make.
- [x] xz
- [x] zlib
- [x] acpid
- [x] alsa-lib
- [x] alsa-utils
- [x] atk
- [x] cairo
- [x] cbindgen
- [x] ccache
- [x] clang
- [x] cmake
- [x] dosfstools
- [x] efibootmgr
- [x] efivar
- [x] eudev
- [x] expat
- [x] ffmpeg
- [ ] firefox
- [x] firefox-bin
- [x] firefox-privacy
- [x] fontconfig
- [x] freetype-harfbuzz
- [x] fribidi
- [x] gdk-pixbuf
- [x] giflib
- [x] glib
- [x] gnupg1
- [x] gperf
- [x] gtk+2
- [x] gtk+3
- [x] hicolor-icon-theme
- [x] intel-media-driver
- [x] intel-vaapi-driver
- [x] lame
- [x] libass
- [x] libdrm
- [x] libepoxy
- [x] liberation-fonts
- [x] libevdev
- [x] libffi
- [x] libinput
- [x] libjpeg-turbo
- [x] libogg
- [x] libpng
- [x] libtheora
- [x] libva
- [x] libva-utils
- [x] libvorbis
- [ ] libvpx
    - `./configure: line 175: perl: not found`
    - `Perl is required to build`
- [x] libwebp
- [x] libxml2
- [x] llvm
- [x] mandoc
- [x] mesa
- [x] meson
- [x] mpv
- [x] mtdev
- [x] nasm
- [x] ncurses
- [x] nodejs
- [x] opendoas
- [x] openssh
- [x] opus
- [x] pango
- [x] python
- [x] python2
- [x] rust
- [x] samurai
- [x] sqlite
- [x] sudo
- [x] tiff
- [x] tzdata
- [x] util-linux
- [x] vim
- [x] wpa_supplicant
- [x] x264
- [x] x265
- [x] xvidcore
- [x] yasm
- [x] zip
- [x] libICE
- [x] libSM
- [x] libX11
- [x] libXScrnSaver
- [x] libXau
- [x] libXcomposite
- [x] libXcursor
- [x] libXdamage
- [x] libXext
- [x] libXfixes
- [x] libXfont2
- [x] libXft
- [x] libXi
- [x] libXinerama
- [x] libXmu
- [x] libXrandr
- [x] libXrender
- [x] libXt
- [x] libXtst
- [x] libXxf86vm
- [x] libfontenc
- [x] libpciaccess
- [x] libxcb
- [x] libxkbcommon
- [x] libxkbfile
- [x] libxshmfence
- [x] pixman
- [x] setxkbmap
- [x] sowm
- [x] st
- [x] xauth
- [x] xbitmaps
- [x] xcb-proto
- [x] xcb-util
- [x] xcb-util-cursor
- [x] xcb-util-image
- [x] xcb-util-keysyms
- [x] xcb-util-renderutil
- [x] xcb-util-wm
- [x] xev
- [x] xf86-input-libinput
- [x] xf86-video-amdgpu
- [x] xf86-video-ati
- [x] xf86-video-intel
- [x] xf86-video-nouveau
- [x] xf86-video-vesa
- [x] xinit
- [x] xinput
- [x] xkbcomp
- [x] xkeyboard-config
    - `perl ./xml2lst.pl < evdev.xml > evdev.lst`
    - `perl ./xml2lst.pl < base.xml > base.lst`
- [x] xorg-server
- [x] xorg-util-macros
- [x] xorgproto
- [x] xprop
- [x] xrandr
- [x] xrdb
- [x] xset
- [x] xsetroot
- [x] xtrans
