### ISSUE TITLE
[Tracker] Bison, Flex, m4, etc removals?

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#170]
- [x] core/baseinit/
 - [x] core/baselayout/
 - [x] core/binutils/ (flex)
 - [x] core/bison/ (m4)
 - [x] core/busybox/
 - [x] core/bzip2/
 - [x] core/curl/
 - [x] core/flex/ (m4)
 - [x] core/gcc/
 - [x] core/git/
 - [x] core/grub/ (bison, flex, m4)
 - [x] core/gzip/
 - [x] core/kiss/
 - [x] core/libressl/
 - [x] core/linux-headers/
 - [x] core/m4/
 - [x] core/make/
 - [x] core/musl/
 - [x] core/pkgconf/
 - [x] core/rsync/
 - [x] core/xz/
 - [x] core/zlib/
 - [x] extra/acpid/
 - [x] extra/alsa-lib/
 - [x] extra/alsa-utils/
 - [x] extra/atk/
 - [x] extra/cairo/
 - [x] extra/cbindgen/
 - [x] extra/ccache/
 - [x] extra/clang/
 - [x] extra/cmake/
 - [x] extra/dhcpcd/
 - [x] extra/dosfstools/
 - [x] extra/e2fsprogs/
 - [x] extra/efibootmgr/
 - [x] extra/efivar/
 - [x] extra/eiwd/
 - [x] extra/eudev/
 - [x] extra/expat/
 - [x] extra/ffmpeg/
 - [x] extra/firefox-bin/
 - [x] extra/firefox-privacy/
 - [x] extra/firefox/
 - [x] extra/fontconfig/
 - [x] extra/freetype-harfbuzz/
 - [x] extra/fribidi/
 - [x] extra/gdk-pixbuf/
 - [x] extra/giflib/
 - [x] extra/glib/
 - [x] extra/gnupg1/
 - [x] extra/gperf/
 - [x] extra/gtk+2/
 - [x] extra/gtk+3/
 - [x] extra/hicolor-icon-theme/
 - [x] extra/intel-vaapi-driver/
 - [x] extra/lame/
 - [x] extra/libass/
 - [x] extra/libdrm/
 - [x] extra/libelf/
 - [x] extra/libepoxy/
 - [x] extra/liberation-fonts/
 - [x] extra/libevdev/
 - [x] extra/libffi/
 - [x] extra/libinput/
 - [x] extra/libjpeg-turbo/
 - [x] extra/libogg/
 - [x] extra/libpng/
 - [x] extra/libtheora/
 - [x] extra/libva-utils/
 - [x] extra/libva/
 - [x] extra/libvorbis/
 - [x] extra/libvpx/
 - [x] extra/libwebp/
 - [x] extra/libxml2/
 - [x] extra/llvm/
 - [x] extra/mandoc/
 - [x] extra/mesa/ (bison, m4, flex)
 - [x] extra/meson/
 - [x] extra/mpv/
 - [x] extra/mtdev/
 - [x] extra/nasm/
 - [x] extra/ncurses/
 - [x] extra/nodejs/
 - [x] extra/opendoas/ (bison)
 - [x] extra/openresolv/
 - [x] extra/openssh/
 - [x] extra/opus/
 - [x] extra/pango/
 - [x] extra/perl/
 - [x] extra/python/
 - [x] extra/python2/
 - [x] extra/rust/
 - [x] extra/samurai/
 - [x] extra/sqlite/
 - [x] extra/sudo/
 - [x] extra/tiff/
 - [x] extra/tzdata/
 - [x] extra/util-linux/
 - [x] extra/vim/
 - [x] extra/wpa_supplicant/
 - [x] extra/x264/
 - [x] extra/x265/
 - [x] extra/xvidcore/
 - [x] extra/zip/
 - [x] testing/gcc/
 - [x] xorg/libICE/
 - [x] xorg/libSM/
 - [x] xorg/libX11/
 - [x] xorg/libXScrnSaver/
 - [x] xorg/libXau/
 - [x] xorg/libXcomposite/
 - [x] xorg/libXcursor/
 - [x] xorg/libXdamage/
 - [x] xorg/libXext/
 - [x] xorg/libXfixes/
 - [x] xorg/libXfont2/
 - [x] xorg/libXft/
 - [x] xorg/libXi/
 - [x] xorg/libXinerama/
 - [x] xorg/libXmu/
 - [x] xorg/libXrandr/
 - [x] xorg/libXrender/
 - [x] xorg/libXt/
 - [x] xorg/libXtst/
 - [x] xorg/libXxf86vm/
 - [x] xorg/libfontenc/
 - [x] xorg/libpciaccess/
 - [x] xorg/libxcb/
 - [x] xorg/libxkbcommon/
 - [x] xorg/libxkbfile/
 - [x] xorg/libxshmfence/
 - [x] xorg/pixman/
 - [x] xorg/setxkbmap/
 - [x] xorg/sowm/
 - [x] xorg/st/
 - [x] xorg/xauth/
 - [x] xorg/xbitmaps/
 - [x] xorg/xcb-proto/
 - [x] xorg/xcb-util-cursor/
 - [x] xorg/xcb-util-image/
 - [x] xorg/xcb-util-keysyms/
 - [x] xorg/xcb-util-renderutil/
 - [x] xorg/xcb-util-wm/
 - [x] xorg/xcb-util/
 - [x] xorg/xev/
 - [x] xorg/xf86-input-libinput/
 - [x] xorg/xf86-video-amdgpu/
 - [x] xorg/xf86-video-ati/
 - [x] xorg/xf86-video-intel/
 - [x] xorg/xf86-video-nouveau/
 - [x] xorg/xf86-video-vesa/
 - [x] xorg/xinit/
 - [x] xorg/xinput/
 - [x] xorg/xkbcomp/
 - [x] xorg/xkeyboard-config/
 - [x] xorg/xorg-server/
 - [x] xorg/xorg-util-macros/
 - [x] xorg/xorgproto/
 - [x] xorg/xprop/
 - [x] xorg/xrandr/
 - [x] xorg/xrdb/
 - [x] xorg/xset/
 - [x] xorg/xsetroot/
 - [x] xorg/xtrans/
