### ISSUE TITLE
[tracker] Testing the new tar code

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#188]
- [x] extra/libinput
- [x] extra/libjpeg-turbo
- [x] extra/libogg
- [x] extra/libpng
- [x] extra/libtheora
- [x] extra/libva
- [x] extra/libva-utils
- [x] extra/libvorbis
- [x] extra/libvpx
- [x] extra/libwebp
- [x] extra/libxml2
- [ ] extra/llvm
- [x] extra/mandoc
- [x] extra/mesa
- [x] extra/meson
- [x] extra/mpv
- [x] extra/mtdev
- [x] extra/nasm
- [x] extra/ncurses
- [x] extra/nodejs
- [x] extra/opendoas
- [x] extra/openresolv
- [x] extra/openssh
- [x] extra/opus
- [x] extra/pango
- [x] extra/perl
- [x] extra/plzip
- [x] extra/python
- [x] extra/python2
- [x] extra/rsync
- [ ] extra/rust
- [x] extra/samurai
- [x] extra/sqlite
- [x] extra/sudo
- [x] extra/tiff
- [x] extra/tzdata
- [x] extra/util-linux
- [x] extra/vim
- [x] extra/wpa_supplicant
- [x] extra/x264
- [x] extra/x265
- [x] extra/xfsprogs
- [x] extra/xvidcore
- [x] extra/zip
- [x] extra/zstd
- [x] xorg/libICE
- [x] xorg/libSM
- [x] xorg/libX11
- [x] xorg/libXScrnSaver
- [x] xorg/libXau
- [x] xorg/libXcomposite
- [x] xorg/libXcursor
- [x] xorg/libXdamage
- [x] xorg/libXext
- [x] xorg/libXfixes
- [x] xorg/libXfont2
- [x] xorg/libXft
- [x] xorg/libXi
- [x] xorg/libXinerama
- [x] xorg/libXmu
- [x] xorg/libXrandr
- [x] xorg/libXrender
- [x] xorg/libXt
- [x] xorg/libXtst
- [x] xorg/libXxf86vm
- [x] xorg/libfontenc
- [x] xorg/libpciaccess
- [x] xorg/libxcb
- [x] xorg/libxkbcommon
- [x] xorg/libxkbfile
- [x] xorg/libxshmfence
- [x] xorg/pixman
- [x] xorg/setxkbmap
- [x] xorg/sowm
- [x] xorg/st
- [x] xorg/xauth
- [x] xorg/xbitmaps
- [x] xorg/xcb-proto
- [x] xorg/xcb-util
- [x] xorg/xcb-util-cursor
- [x] xorg/xcb-util-image
- [x] xorg/xcb-util-keysyms
- [x] xorg/xcb-util-renderutil
- [x] xorg/xcb-util-wm
- [x] xorg/xev
- [x] xorg/xf86-input-libinput
- [x] xorg/xf86-video-amdgpu
- [x] xorg/xf86-video-ati
- [x] xorg/xf86-video-intel
- [x] xorg/xf86-video-nouveau
- [x] xorg/xf86-video-vesa
- [x] xorg/xinit
- [x] xorg/xinput
- [x] xorg/xkbcomp
- [x] xorg/xkeyboard-config
- [x] xorg/xorg-server
- [x] xorg/xorg-util-macros
- [x] xorg/xorgproto
- [x] xorg/xprop
- [x] xorg/xrandr
- [x] xorg/xrdb
- [x] xorg/xset
- [x] xorg/xsetroot
- [x] xorg/xtrans

**Comment by dylanaraps** [comment]
Everything works!
