### ISSUE TITLE
[tracker] make pkgconf an explicit dependency

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#216]
- [x] core/baseinit
- [x] core/baselayout
- [x] core/binutils
- [x] core/bison
- [x] core/busybox
- [x] core/bzip2
- [x] core/curl
- [x] core/flex
- [x] core/gcc
- [x] core/git
- [x] core/grub
- [x] core/gzip
- [x] core/kiss
- [x] core/libressl
- [x] core/linux-headers
- [x] core/m4
- [x] core/make
- [x] core/musl
- [x] core/pkgconf
- [x] core/xz
- [x] core/zlib
- [x] extra/acpid
- [x] extra/alsa-lib
- [x] extra/alsa-utils
- [ ] extra/atk (starts cloning dependencies if absent)
- [ ] extra/cairo (configure errors out)
- [x] extra/cbindgen
- [x] extra/ccache
- [x] extra/clang
- [x] extra/cmake
- [x] extra/dhcpcd
- [x] extra/dosfstools
- [x] extra/e2fsprogs
- [ ] extra/efibootmgr (build errors)
- [x] extra/efivar
- [x] extra/eiwd
- [x] extra/eudev
- [x] extra/expat
- [ ] extra/ffmpeg (configure errors out)
- [ ] extra/firefox (yes)
- [x] extra/firefox-bin
- [ ] extra/firefox-esr (yes)
- [x] extra/firefox-esr-bin
- [x] extra/firefox-privacy
- [ ] extra/fontconfig (configure errors out)
- [ ] extra/freetype-harfbuzz  (configure errors out)
- [x] extra/fribidi
- [x] extra/gcompat
- [ ] extra/gdk-pixbuf (starts cloning dependencies if absent)
- [x] extra/giflib
- [ ] extra/glib (starts cloning dependencies if absent)
- [x] extra/gnupg1
- [x] extra/gperf
- [ ] extra/gtk+2 (configure errors out)
- [ ] extra/gtk+3 (configure errors out)
- [x] extra/hicolor-icon-theme
- [ ] extra/intel-vaapi-driver (configure errors out)
- [x] extra/lame
- [ ] extra/libass  (configure errors out)
- [ ] extra/libdrm  (configure errors out)
- [x] extra/libelf
- [x] extra/libepoxy
- [x] extra/liberation-fonts
- [x] extra/libevdev
- [x] extra/libffi
- [ ] extra/libinput (build needs it to check for udev (our side of the fence))
- [x] extra/libjpeg-turbo
- [x] extra/libogg
- [x] extra/libpng
- [x] extra/libtheora
- [x] extra/libudev-zero
- [ ] extra/libva (configure errors out)
- [ ] extra/libva-utils (configure errors out)
- [x] extra/libvorbis
- [x] extra/libvpx
- [x] extra/libwebp
- [x] extra/libxml2
- [x] extra/llvm
- [x] extra/mandoc
- [ ] extra/mesa (configure errors out)
- [x] extra/meson
- [ ] extra/mpv (configure errors out)
- [x] extra/mtdev
- [x] extra/nasm
- [x] extra/ncurses
- [x] extra/nodejs
- [x] extra/opendoas
- [x] extra/openresolv
- [x] extra/openssh
- [x] extra/opus
- [ ] extra/pango (starts cloning dependencies if absent)
- [x] extra/perl
- [x] extra/plzip
- [x] extra/python
- [x] extra/python2
- [x] extra/rsync
- [ ] extra/rust (yes)
- [x] extra/samurai
- [x] extra/sqlite
- [x] extra/sudo
- [x] extra/tiff
- [x] extra/tzdata
- [x] extra/util-linux
- [x] extra/vim
- [x] extra/wpa_supplicant
- [x] extra/x264
- [x] extra/x265
- [x] extra/xfsprogs
- [x] extra/xvidcore
- [x] extra/zip
- [x] extra/zstd
- [ ] xorg/libICE (configure errors out)
- [ ] xorg/libSM (configure errors out)
- [ ] xorg/libX11 (configure errors out)
- [ ] xorg/libXScrnSaver (configure errors out)
- [ ] xorg/libXau (configure errors out)
- [ ] xorg/libXcomposite (configure errors out)
- [ ] xorg/libXcursor (configure errors out)
- [ ] xorg/libXdamage (configure errors out)
- [ ] xorg/libXext (configure errors out)
- [ ] xorg/libXfixes (configure errors out)
- [ ] xorg/libXfont2 (configure errors out)
- [ ] xorg/libXft (configure errors out)
- [ ] xorg/libXi (configure errors out)
- [ ] xorg/libXinerama (configure errors out)
- [ ] xorg/libXmu (configure errors out)
- [ ] xorg/libXrandr (configure errors out)
- [ ] xorg/libXrender (configure errors out)
- [ ] xorg/libXt (configure errors out)
- [ ] xorg/libXtst (configure errors out)
- [ ] xorg/libXxf86vm (configure errors out)
- [ ] xorg/libfontenc (configure errors out)
- [x] xorg/libpciaccess 
- [ ] xorg/libxcb (configure errors out)
- [ ] xorg/libxkbcommon (configure errors out)
- [ ] xorg/libxkbfile (configure errors out)
- [ ] xorg/libxshmfence (configure errors out)
- [x] xorg/pixman 
- [ ] xorg/setxkbmap (configure errors out)
- [x] xorg/sowm
- [ ] xorg/st (build errors out)
- [ ] xorg/xauth (configure errors out)
- [x] xorg/xbitmaps
- [x] xorg/xcb-proto
- [ ] xorg/xcb-util (configure errors out)
- [ ] xorg/xcb-util-cursor (configure errors out)
- [ ] xorg/xcb-util-image (configure errors out)
- [ ] xorg/xcb-util-keysyms (configure errors out)
- [ ] xorg/xcb-util-renderutil (configure errors out)
- [ ] xorg/xcb-util-wm (configure errors out)
- [ ] xorg/xev (configure errors out)
- [ ] xorg/xf86-input-libinput (configure errors out)
- [ ] xorg/xf86-video-amdgpu (configure errors out)
- [ ] xorg/xf86-video-ati (configure errors out)
- [ ] xorg/xf86-video-intel (configure errors out)
- [ ] xorg/xf86-video-nouveau (configure errors out)
- [ ] xorg/xf86-video-vesa (configure errors out)
- [ ] xorg/xinit (configure errors out)
- [ ] xorg/xinput (configure errors out)
- [ ] xorg/xkbcomp (configure errors out)
- [ ] xorg/xkeyboard-config (configure errors out)
- [ ] xorg/xorg-server (configure errors out)
- [x] xorg/xorg-util-macros
- [x] xorg/xorgproto
- [ ] xorg/xprop (configure errors out)
- [ ] xorg/xrandr (configure errors out)
- [ ] xorg/xrdb (configure errors out)
- [ ] xorg/xset (configure errors out)
- [ ] xorg/xsetroot (configure errors out)
- [ ] xorg/xtrans (configure errors out)
