### ISSUE TITLE
[tracker] make make an explicit dependency

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#217]
Maybe, maybe not. We'll see. Ticked boxes are packages which require make.

- [ ] core/baseinit
- [ ] core/baselayout
- [x] core/binutils
- [x] core/bison
- [x] core/busybox
- [x] core/bzip2
- [x] core/curl
- [x] core/flex
- [x] core/gcc
- [x] core/git
- [x] core/grub
- [x] core/gzip
- [ ] core/kiss
- [x] core/libressl
- [x] core/linux-headers
- [x] core/m4
- [x] core/make
- [x] core/musl
- [x] core/pkgconf
- [x] core/xz
- [x] core/zlib
- [x] extra/acpid
- [x] extra/alsa-lib
- [x] extra/alsa-utils
- [ ] extra/atk
- [x] extra/cairo
- [ ] extra/cbindgen
- [x] extra/ccache
- [ ] extra/clang
- [ ] extra/cmake
- [x] extra/dhcpcd
- [x] extra/dosfstools
- [x] extra/e2fsprogs
- [x] extra/efibootmgr
- [x] extra/efivar
- [x] extra/eiwd
- [x] extra/eudev
- [x] extra/expat
- [x] extra/ffmpeg
- [x] extra/firefox
- [ ] extra/firefox-bin
- [x] extra/firefox-esr
- [ ] extra/firefox-esr-bin
- [ ] extra/firefox-privacy
- [x] extra/fontconfig
- [x] extra/freetype-harfbuzz
- [x] extra/fribidi
- [x] extra/gcompat
- [ ] extra/gdk-pixbuf
- [x] extra/giflib
- [ ] extra/glib
- [x] extra/gnupg1
- [x] extra/gperf
- [x] extra/gtk+2
- [x] extra/gtk+3
- [x] extra/hicolor-icon-theme
- [ ] extra/intel-vaapi-driver
- [x] extra/lame
- [x] extra/libass
- [ ] extra/libdrm
- [x] extra/libelf
- [ ] extra/libepoxy
- [ ] extra/liberation-fonts
- [x] extra/libevdev
- [x] extra/libffi
- [ ] extra/libinput
- [ ] extra/libjpeg-turbo
- [x] extra/libogg
- [x] extra/libpng
- [x] extra/libtheora
- [x] extra/libudev-zero
- [x] extra/libva
- [x] extra/libva-utils
- [x] extra/libvorbis
- [x] extra/libvpx
- [x] extra/libwebp
- [x] extra/libxml2
- [ ] extra/llvm
- [x] extra/mandoc
- [ ] extra/mesa
- [ ] extra/meson
- [ ] extra/mpv
- [x] extra/mtdev
- [x] extra/nasm
- [x] extra/ncurses
- [ ] extra/nodejs
- [x] extra/opendoas
- [x] extra/openresolv
- [x] extra/openssh
- [x] extra/opus
- [ ] extra/pango
- [x] extra/perl
- [x] extra/plzip
- [x] extra/python
- [x] extra/python2
- [x] extra/rsync
- [ ] extra/rust
- [x] extra/samurai
- [x] extra/sqlite
- [x] extra/sudo
- [x] extra/tiff
- [x] extra/tzdata
- [x] extra/util-linux
- [x] extra/vim
- [x] extra/wpa_supplicant
- [x] extra/x264
- [x] extra/x265
- [x] extra/xfsprogs
- [x] extra/xvidcore
- [x] extra/zip
- [x] extra/zstd
- [x] xorg/libICE
- [x] xorg/libSM
- [x] xorg/libX11
- [x] xorg/libXScrnSaver
- [x] xorg/libXau
- [x] xorg/libXcomposite
- [x] xorg/libXcursor
- [x] xorg/libXdamage
- [x] xorg/libXext
- [x] xorg/libXfixes
- [x] xorg/libXfont2
- [x] xorg/libXft
- [x] xorg/libXi
- [x] xorg/libXinerama
- [x] xorg/libXmu
- [x] xorg/libXrandr
- [x] xorg/libXrender
- [x] xorg/libXt
- [x] xorg/libXtst
- [x] xorg/libXxf86vm
- [x] xorg/libfontenc
- [x] xorg/libpciaccess
- [x] xorg/libxcb
- [ ] xorg/libxkbcommon
- [x] xorg/libxkbfile
- [x] xorg/libxshmfence
- [x] xorg/pixman
- [x] xorg/setxkbmap
- [x] xorg/sowm
- [x] xorg/st
- [x] xorg/xauth
- [x] xorg/xbitmaps
- [x] xorg/xcb-proto
- [x] xorg/xcb-util
- [x] xorg/xcb-util-cursor
- [x] xorg/xcb-util-image
- [x] xorg/xcb-util-keysyms
- [x] xorg/xcb-util-renderutil
- [x] xorg/xcb-util-wm
- [x] xorg/xev
- [x] xorg/xf86-input-libinput
- [x] xorg/xf86-video-amdgpu
- [x] xorg/xf86-video-ati
- [ ] xorg/xf86-video-intel
- [x] xorg/xf86-video-nouveau
- [x] xorg/xf86-video-vesa
- [x] xorg/xinit
- [x] xorg/xinput
- [x] xorg/xkbcomp
- [x] xorg/xkeyboard-config
- [x] xorg/xorg-server
- [x] xorg/xorg-util-macros
- [x] xorg/xorgproto
- [x] xorg/xprop
- [x] xorg/xrandr
- [x] xorg/xrdb
- [x] xorg/xset
- [x] xorg/xsetroot
- [x] xorg/xtrans

**Comment by dylanaraps** [comment]
Will revisit this at a later date.
