### ISSUE TITLE
[Tracker] GTK+3 packaging

### ISSUE THREAD

**Issue by konimex** [kisslinux/repo#41]
Using BLFS as reference, the strict dependencies are:

- [x] <s>at-spi2-atk</s> a bridge to a dbus service, [use Sabotage's package](https://github.com/sabotage-linux/atk-bridge-fake)
  - [x] atk
    - [x] glib
  - [ ] <s>at-spi2-core</s>
- [x] fribidi (in ffmpeg tree)
- [x] gdk-pixbuf
  - [x] glib
    - [x] libxslt
      - [x] libxml2
  - [x] libjpeg-turbo
  - [x] libpng
  - [x] shared-mime-info (probably optional)
- [x] libepoxy
  - [x] mesa
- [ ] pango
  - [ ] fontconfig
    - [ ] freetype + harfbuzz
  - [x] fribidi
  - [x] glib

Of course, this does not include `makedepends`.

**Comment by konimex** [comment]
Closing as this package is successfully built.
