### ISSUE TITLE
[Tracker] Packages fixes

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#73]
- [x] `cairo`
    - [x] Build without debug utilities.
    - [ ] ~~Remove `libpng` dependency if possible.~~
        - Not possible. :(
    - [x] References: [1](https://gist.github.com/nddrylliog/8870134)
- [x] `aria2`
    - [x] Fix dependencies.
    - [x] Remove docs.
