### ISSUE TITLE
[Tracker] The great GCC 9.2 rebuild.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#84]
- [x] core/autoconf
- [x] core/automake
- [x] core/baseinit
- [x] core/baselayout
- [x] core/binutils
- [x] core/bison
- [x] core/busybox
- [x] core/bzip2
- [x] core/ca-certificates
- [x] core/curl
- [x] core/dhcpcd
- [x] core/e2fsprogs
- [x] core/eudev
- [x] core/fakeroot
- [x] core/file
- [x] core/flex
- [x] core/gcc
- [x] core/git
- [x] core/grub
- [x] core/gzip
- [x] core/kiss
- [x] core/kiss-bootstrap
- [x] core/libelf
- [x] core/libnl
- [x] core/libressl
- [x] core/linux-headers
- [x] core/m4
- [x] core/make
- [x] core/mandoc
- [x] core/musl
- [x] core/perl
- [x] core/pkgconf
- [x] core/rsync
- [x] core/util-linux
- [x] core/wpa_supplicant
- [x] core/xz
- [x] core/zlib
- [x] extra/alsa-lib
- [x] extra/alsa-utils
- [x] extra/atk
- [x] extra/atk-bridge-fake
- [x] extra/bash
- [x] extra/cargo
    - Blocker: current bad internet connection
- [x] extra/cbindgen
    - Blocker: current bad internet connection
- [x] extra/ccache
- [x] extra/clang
- [x] extra/cmake
- [x] extra/cryptsetup
- [x] extra/efibootmgr
- [x] extra/efivar
- [x] extra/expat
- [x] extra/ffmpeg
- [x] extra/firefox
- [x] extra/fribidi
- [x] extra/giflib
- [x] extra/glib
- [x] extra/gmp
- [x] extra/go
- [x] extra/gperf
- [x] extra/iana-etc
- [x] extra/imlib2
- [x] extra/json-c
- [x] extra/kbd
- [x] extra/lame
- [x] extra/libaio
- [x] extra/libass
- [x] extra/libffi
- [x] extra/libjpeg-turbo
- [x] extra/libogg
- [x] extra/libpng
- [x] extra/libtheora
- [x] extra/libtool
- [x] extra/libvorbis
- [x] extra/libvpx
- [x] extra/libwebp
- [x] extra/libxml2
- [x] extra/libxslt
- [x] extra/linux-firmware
- [x] extra/llvm
- [x] extra/lvm2
- [x] extra/meson
- [x] extra/mpv
- [x] extra/nasm
- [x] extra/ncurses
- [x] extra/ninja
- [x] extra/nodejs
- [x] extra/openssh
- [x] extra/opus
- [x] extra/popt
- [x] extra/python
- [x] extra/python-setuptools
- [x] extra/python2
- [x] extra/rust
    - Blocker: current bad internet connection
- [x] extra/shared-mime-info
- [x] extra/sudo
- [x] extra/tiff
- [x] extra/tzdata
- [x] extra/vim
- [x] extra/wavpack
- [x] extra/x264
- [x] extra/x265
- [x] extra/xvidcore
- [x] extra/yasm
- [x] extra/zip
- [x] xorg/cairo
- [x] xorg/fontconfig
- [x] xorg/freetype-harfbuzz
- [x] xorg/gdk-pixbuf
- [x] xorg/gtk+2
- [x] xorg/gtk+3
- [x] xorg/libICE
- [x] xorg/libSM
- [x] xorg/libX11
- [x] xorg/libXScrnSaver
- [x] xorg/libXau
- [x] xorg/libXcomposite
- [x] xorg/libXcursor
- [x] xorg/libXdamage
- [x] xorg/libXext
- [x] xorg/libXfixes
- [x] xorg/libXfont2
- [x] xorg/libXft
- [x] xorg/libXi
- [x] xorg/libXinerama
- [x] xorg/libXmu
- [x] xorg/libXrandr
- [x] xorg/libXrender
- [x] xorg/libXt
- [x] xorg/libXtst
- [x] xorg/libXxf86vm
- [x] xorg/libdrm
- [x] xorg/libepoxy
- [x] xorg/libevdev
- [x] xorg/libfontenc
- [x] xorg/libinput
- [x] xorg/libpciaccess
- [x] xorg/libxcb
- [x] xorg/libxkbfile
- [x] xorg/libxshmfence
- [x] xorg/mesa
- [x] xorg/mtdev
- [x] xorg/pango
- [x] xorg/pixman
- [x] xorg/python-mako
- [x] xorg/st
- [x] xorg/xcb-proto
- [x] xorg/xcb-util
- [x] xorg/xcb-util-keysyms
- [x] xorg/xcb-util-wm
- [x] xorg/xf86-input-libinput
- [x] xorg/xinit
- [x] xorg/xkbcomp
- [x] xorg/xkeyboard-config
- [x] xorg/xorg-server
- [x] xorg/xorg-util-macros
- [x] xorg/xorgproto
- [x] xorg/xrdb
- [x] xorg/xset
- [x] xorg/xtrans
